# -*- coding: utf-8 -*-
"""Score

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t_G9L3NldocpxpJ0O3qq8DGjtJhugYb_
"""

scores = list(map(int, input().split()))

average=sum(scores)/len(scores)

print(average)